### ISSUE TITLE
Error when uploading document.

### ISSUE THREAD

**Issue by samuelmorais** [aietal/aimengpt#1]
Hi,
I installed the system and it works very well, congrats.

I have an error, though,  when trying to upload a PDF.

index-2823173ce2dd41d0.js:1 Error uploading file: Error: Network Error
    at e.exports (733-3a0e42c42b71aae8.js:1:16247)
    at b.onerror (733-3a0e42c42b71aae8.js:1:11261)
(anonymous) @ index-2823173ce2dd41d0.js:1
:3000/api/inject-documents:1     Failed to load resource: net::ERR_EMPTY_RESPONSE

I tried in Chrome and Firefox. I am running the system under localhost 3000.

These are the screenshots of the error:
![image](https://github.com/aietal/aimengpt/assets/19518700/8b40cc4a-4df8-40ca-abf3-097efbd6a1b7)

![image](https://github.com/aietal/aimengpt/assets/19518700/2da1f064-b96d-4af4-9efc-5b2de15cea43)

**Comment by samuelmorais** [comment]
Now I managed to upload a document. Looks like the problem was with the file.
